name: Linux

on:
  [push, pull_request]

jobs:
  linux_build:
    name: Build MeshLab Extra Plugins (Linux)
    runs-on: ubuntu-16.04 #in order to deploy, need to use oldest supported version
    strategy:
      matrix:
        precision: [single_precision, double_precision]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: checkout sub-submodule vcg
      run: |
        cd meshlab
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.3'
    - name: Install dependencies
      run: |
       sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libgmp-dev
       #needed by qt 5.15 on linux
       #sudo apt-get install libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-render-util0-dev libxcb-xinerama0-dev
    - name: Setup env variables
      id: envs
      shell: bash
      run: |
        if [ "${{matrix.precision}}" == "double_precision" ]; then
          echo  ::set-output name=doption::"-DBUILD_WITH_DOUBLE_SCALAR=ON"
          echo  ::set-output name=artifact_suffix::"_double"
        else
          echo  ::set-output name=doption::""
          echo  ::set-output name=artifact_suffix::""
        fi
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DMESHLAB_IS_NIGHTLY_VERSION=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH ${{steps.envs.outputs.doption}} ..
        make -j4
    - name: Upload MeshLab Extra Plugins
      uses: actions/upload-artifact@v2
      with:
        name: meshlab_linux_extra_plugins${{steps.envs.outputs.artifact_suffix}}
        path: build/meshlab/src/distrib/plugins
