name: Windows

on:
  [push, pull_request]

jobs:
  windows_build:
    name: Build MeshLab Extra Plugins (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        precision: [single_precision, double_precision]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: checkout sub-submodule vcg
      run: |
        cd meshlab
        $auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Setup env variables
      id: envs
      shell: bash
      run: |
        if [ "${{matrix.precision}}" == "double_precision" ]; then
          echo  ::set-output name=doption::"-DBUILD_WITH_DOUBLE_SCALAR=ON"
          echo  ::set-output name=artifact_suffix::"_double"
        else
          echo  ::set-output name=doption::""
          echo  ::set-output name=artifact_suffix::""
        fi
    - name: Configure and Build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH ${{steps.envs.outputs.doption}} ..
        nmake
    - name: Upload MeshLab Extra Plugins
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_windows_extra_plugins${{steps.envs.outputs.artifact_suffix}}
        path: build/distrib/plugins
